use_frameworks!

platform :ios, '10.0'

target 'MPLocationManager_Example' do
  pod 'MPLocationManager', :path => '/Users/hemantagrawal/Desktop/Mohak/MPLocationManager/MPLocationManager.podspec'

end
